language: node_js
node_js:
  - "0.10"
  - "0.12"

notifications:
  email:
    - johnny.estilles@agentia.asia

addons:
  code_climate:
    repo_token: e090b1a7614cd2d41074b72737076622befc41ea65999f267fd4121078e8b8fd

before_install:
  - npm install -g eslint
  - npm install -g codeclimate-test-reporter

before_script:
  - npm run lint

after_script:
  - npm run cover
  - codeclimate < ./coverage/lcov.info

branches:
  only:
    - master
